import type {
  OverviewStats,
  QueryDetail,
  QuerySummary,
  SystemHealth,
} from './types'

export const demoQueries: QuerySummary[] = [
  {
    id: 'q-7f21a',
    queryId: '520730',
    serverId: 1,
    databaseId: 16384,
    fingerprint: '7f21ad8c',
    title: 'Sipariş geçmişi ve müşteri özeti',
    sqlPreview: 'SELECT o.id, o.created_at, c.name, SUM(oi.quantity * oi.price)…',
    database: 'commerce',
    calls: 18420,
    avgDurationMs: 428,
    totalTimeMs: 7883760,
    impactScore: 92,
    severity: 'critical',
    lastSeenAt: '2026-07-22T10:42:00Z',
    changePercent: 18.4,
    hasComparison: true,
  },
  {
    id: 'q-a931b',
    queryId: '693019',
    serverId: 1,
    databaseId: 16384,
    fingerprint: 'a931bc20',
    title: 'Aktif ürün kataloğu araması',
    sqlPreview: "SELECT p.* FROM products p WHERE lower(p.name) LIKE '%' || $1 || '%'…",
    database: 'commerce',
    calls: 9204,
    avgDurationMs: 196,
    totalTimeMs: 1803984,
    impactScore: 68,
    severity: 'warning',
    lastSeenAt: '2026-07-22T10:41:00Z',
    changePercent: -6.2,
    hasComparison: true,
  },
  {
    id: 'q-df208',
    queryId: '913928',
    serverId: 1,
    databaseId: 16385,
    fingerprint: 'df208e14',
    title: 'Bekleyen ödeme mutabakatı',
    sqlPreview: 'SELECT p.provider, COUNT(*), SUM(p.amount) FROM payments p…',
    database: 'billing',
    calls: 3120,
    avgDurationMs: 882,
    totalTimeMs: 2751840,
    impactScore: 88,
    severity: 'critical',
    lastSeenAt: '2026-07-22T10:38:00Z',
    changePercent: 31.7,
    hasComparison: true,
  },
  {
    id: 'q-44ce0',
    queryId: '281824',
    serverId: 1,
    databaseId: 16386,
    fingerprint: '44ce0f9b',
    title: 'Günlük stok hareketleri',
    sqlPreview: 'SELECT warehouse_id, product_id, SUM(delta) FROM stock_movements…',
    database: 'inventory',
    calls: 1440,
    avgDurationMs: 122,
    totalTimeMs: 175680,
    impactScore: 54,
    severity: 'warning',
    lastSeenAt: '2026-07-22T10:32:00Z',
    changePercent: -22.8,
    hasComparison: true,
  },
  {
    id: 'q-f90c4',
    queryId: '1018340',
    serverId: 1,
    databaseId: 16387,
    fingerprint: 'f90c421e',
    title: 'Kullanıcı oturum doğrulaması',
    sqlPreview: 'SELECT id, role, last_login_at FROM users WHERE id = $1 AND active…',
    database: 'identity',
    calls: 45280,
    avgDurationMs: 8.4,
    totalTimeMs: 380352,
    impactScore: 8,
    severity: 'healthy',
    lastSeenAt: '2026-07-22T10:43:00Z',
    changePercent: -2.1,
    hasComparison: false,
  },
  {
    id: 'q-11b2f',
    queryId: '725807',
    serverId: 1,
    databaseId: 16384,
    fingerprint: '11b2f891',
    title: 'Kampanya hedef kitle seçimi',
    sqlPreview: 'WITH customer_totals AS (SELECT customer_id, SUM(total)…',
    database: 'commerce',
    calls: 288,
    avgDurationMs: 2480,
    totalTimeMs: 714240,
    impactScore: 86,
    severity: 'critical',
    lastSeenAt: '2026-07-22T10:24:00Z',
    changePercent: 9.8,
    hasComparison: true,
  },
]

export const demoOverview: OverviewStats = {
  databaseName: 'commerce-prod',
  environment: 'Üretim',
  lastCollectedAt: '2026-07-22T10:43:00Z',
  queriesAnalyzed: 1276,
  criticalQueries: 17,
  regressions: 6,
  databaseTimeHours: 28.4,
  latencyTrend: [
    { label: 'Pzt', value: 238 }, { label: 'Sal', value: 228 }, { label: 'Çar', value: 242 },
    { label: 'Per', value: 211 }, { label: 'Cum', value: 205 }, { label: 'Cmt', value: 191 },
    { label: 'Paz', value: 184 },
  ],
  recentActivity: [
    { id: 'a1', title: 'Toplama tamamlandı', detail: '1.276 sorgu örneği işlendi', occurredAt: '2026-07-22T10:43:00Z', tone: 'healthy' },
    { id: 'a2', title: 'Yeni kritik bulgu', detail: 'Ödeme mutabakatında sıralı tarama', occurredAt: '2026-07-22T10:38:00Z', tone: 'critical' },
    { id: 'a3', title: 'İyileştirme doğrulandı', detail: 'Stok sorgusu gecikmesi %23 düştü', occurredAt: '2026-07-22T09:52:00Z', tone: 'healthy' },
  ],
  opportunities: [
    { queryId: 'q-df208', title: 'Bekleyen ödeme mutabakatı', averageMs: 882, loadPercent: 18.4 },
    { queryId: 'q-7f21a', title: 'Sipariş geçmişi ve müşteri özeti', averageMs: 428, loadPercent: 14.2 },
    { queryId: 'q-11b2f', title: 'Kampanya hedef kitle seçimi', averageMs: 2480, loadPercent: 9.8 },
  ],
}

export const demoQueryDetails: Record<string, QueryDetail> = Object.fromEntries(
  demoQueries.map((query, index) => [query.id, {
    ...query,
    fullSql: index === 0
      ? `SELECT o.id, o.created_at, c.name,\n       SUM(oi.quantity * oi.price) AS total\nFROM orders o\nJOIN customers c ON c.id = o.customer_id\nJOIN order_items oi ON oi.order_id = o.id\nWHERE o.created_at >= $1\n  AND c.tenant_id = $2\nGROUP BY o.id, o.created_at, c.name\nORDER BY o.created_at DESC\nLIMIT 100;`
      : `${query.sqlPreview.replace('…', '')}\nWHERE created_at >= $1\nORDER BY created_at DESC\nLIMIT $2;`,
    firstSeenAt: '2026-07-08T07:20:00Z',
    p95DurationMs: query.avgDurationMs * 1.82,
    rowsPerCall: 74,
    sharedBlocksHit: 8192,
    sharedBlocksRead: 1840,
    trend: [
      { label: '16 Tem', durationMs: query.avgDurationMs * 1.26, impactScore: Math.max(0, query.impactScore - 9) },
      { label: '17 Tem', durationMs: query.avgDurationMs * 1.14, impactScore: Math.max(0, query.impactScore - 7) },
      { label: '18 Tem', durationMs: query.avgDurationMs * 1.21, impactScore: Math.max(0, query.impactScore - 5) },
      { label: '19 Tem', durationMs: query.avgDurationMs * .98, impactScore: Math.max(0, query.impactScore - 4) },
      { label: '20 Tem', durationMs: query.avgDurationMs * 1.08, impactScore: Math.max(0, query.impactScore - 2) },
      { label: '21 Tem', durationMs: query.avgDurationMs * 1.02, impactScore: Math.max(0, query.impactScore - 1) },
      { label: '22 Tem', durationMs: query.avgDurationMs, impactScore: query.impactScore },
    ],
    scoreBreakdown: [
      { key: 'latency', label: 'Toplam süre', contribution: Math.min(25, Math.round(query.impactScore * .3)), maxContribution: 25, hint: 'Toplam çalışma süresinin etkisi' },
      { key: 'io', label: 'Okunan shared blok', contribution: Math.min(25, Math.round(query.impactScore * .25)), maxContribution: 25, hint: 'Shared blok okuma yükü' },
      { key: 'regression', label: 'Yavaşlama', contribution: Math.min(25, Math.round(query.impactScore * .2)), maxContribution: 25, hint: 'Önceki döneme göre değişim' },
      { key: 'frequency', label: 'Çağrı sıklığı', contribution: Math.min(25, Math.round(query.impactScore * .25)), maxContribution: 25, hint: 'Çağrı sayısının toplam etkisi' },
    ],
    comparison: [
      { metric: 'Ort. gecikme', before: query.avgDurationMs, after: query.avgDurationMs * .36, unit: 'ms', improvementPercent: 64 },
      { metric: 'Okunan blok', before: 1840, after: 312, unit: 'blok', improvementPercent: 83 },
      { metric: 'Tahmini maliyet', before: 8420, after: 2710, unit: 'cost', improvementPercent: 68 },
    ],
    findings: [
      { id: 'f1', severity: 'critical', title: 'Yüksek shared blok okuması', description: 'Bu sorgu seçili dönemde belirgin bir okuma yükü oluşturuyor.', recommendation: 'Sorgu planını gerçek parametreler ve buffer ölçümleriyle doğrulayın.' },
      { id: 'f2', severity: 'warning', title: 'Yüksek toplam çalışma süresi', description: 'Çağrı sayısı ve ortalama süre birlikte toplam etkiyi yükseltiyor.', recommendation: 'En yoğun kullanım senaryosunu ölçüp sorgu planındaki pahalı adımları inceleyin.' },
    ],
  }]),
) as Record<string, QueryDetail>

const history = (values: number[]) => values.map((value, index) => ({
  label: `${index * 4}:00`,
  value,
}))

export const demoHealth: SystemHealth = {
  collectedAt: '2026-07-22T10:43:00Z',
  postgresVersion: '16.4',
  overall: 'warning',
  metrics: [
    { key: 'connections', label: 'Bağlantı kullanımı', value: 64, unit: '%', target: '< %80', severity: 'healthy', description: '128 / 200 bağlantı aktif', history: history([46, 48, 52, 58, 61, 64]) },
    { key: 'cache', label: 'Cache hit oranı', value: 98.7, unit: '%', target: '> %99', severity: 'warning', description: 'Son 24 saat paylaşımlı buffer', history: history([99.1, 99, 98.9, 98.8, 98.7, 98.7]) },
    { key: 'cpu', label: 'CPU kullanımı', value: 42, unit: '%', target: '< %75', severity: 'healthy', description: '15 dakika hareketli ortalama', history: history([28, 32, 31, 39, 46, 42]) },
    { key: 'storage', label: 'Disk kullanımı', value: 71, unit: '%', target: '< %80', severity: 'warning', description: '412 GB / 580 GB', history: history([68, 68.4, 69, 69.8, 70.4, 71]) },
  ],
  databases: [
    { serverId: 1, databaseId: 16384, name: 'commerce', sizeGb: 284, tableCount: 42, sequentialScans: 842, indexScans: 12042, deadTuples: 18240, signals: 0, severity: 'healthy' },
    { serverId: 1, databaseId: 16385, name: 'billing', sizeGb: 96, tableCount: 18, sequentialScans: 1184, indexScans: 8420, deadTuples: 92400, signals: 2, severity: 'warning' },
    { serverId: 1, databaseId: 16386, name: 'inventory', sizeGb: 32, tableCount: 23, sequentialScans: 96, indexScans: 7280, deadTuples: 4280, signals: 0, severity: 'healthy' },
  ],
  capabilities: [
    { key: 'seqScan', label: 'Seq Scan', available: true, source: 'PoWA pg_stat_all_tables' },
    { key: 'deadTuple', label: 'Dead tuple', available: true, source: 'PoWA pg_stat_all_tables' },
    { key: 'autovacuum', label: 'Autovacuum', available: true, source: 'PoWA pg_stat_all_tables' },
  ],
}
