import type {
  CapabilityMatrixData,
  DatabaseOptimizeData,
  OverviewStats,
  QueryDetail,
  QuerySummary,
  SystemHealth,
} from './types'

const demoWaits: QuerySummary['waits'] = {
  capability: {
    available: true,
    version: '1.1',
    release: '1.1.11',
    dataAvailable: true,
    source: 'PoWA pg_wait_sampling',
    coverage: 'TOP_LEVEL_SAMPLED_WAITS',
    reason: 'Sampled wait dağılımı kullanılabilir.',
  },
  totalSamples: 240,
  categories: { io: 132, lock: 48, lwlock: 20, client: 12, ipc: 8, timeout: 4, activity: 0, extension: 0, other: 16 },
  dominant: { category: 'IO', event: 'DataFileRead', sharePercent: 55, confidence: 'MEDIUM' },
  events: [
    { category: 'IO', eventType: 'IO', event: 'DataFileRead', samples: 132, sharePercent: 55 },
    { category: 'LOCK', eventType: 'Lock', event: 'transactionid', samples: 48, sharePercent: 20 },
  ],
  scoreIncluded: false,
}

export const demoQueries: QuerySummary[] = [
  {
    id: 'q-7f21a',
    queryId: '520730',
    serverId: 1,
    databaseId: 16384,
    fingerprint: '7f21ad8c',
    title: 'Sipariş geçmişi ve müşteri özeti',
    sqlPreview: 'SELECT o.id, o.created_at, c.name, SUM(oi.quantity * oi.price)…',
    database: 'commerce',
    calls: 18420,
    avgDurationMs: 428,
    totalTimeMs: 7883760,
    dbLoadPercent: 24.8,
    sharedBlocksHit: 8_920_000,
    sharedBlocksRead: 1840,
    tempBlocksWritten: 48,
    walBytes: 0,
    cpu: { capability: { available: true, version: '2.3.2', dataAvailable: true, source: 'PoWA pg_stat_kcache', coverage: 'EXECUTION_ONLY', reason: 'CPU ve filesystem sayaçları kullanılabilir.' }, userTimeMs: 4_910_000, systemTimeMs: 620_000, totalTimeMs: 5_530_000, percentOfExecTime: 70.1, filesystemReadsBytes: 48_000_000, filesystemWritesBytes: 8_000_000, scoreIncluded: false },
    waits: demoWaits,
    impactScore: 92,
    priority: 'CRITICAL',
    severity: 'critical',
    observedFrom: '2026-07-21T10:42:00Z', observedTo: '2026-07-22T10:42:00Z', coveragePercent: 100,
    resetDetected: false, comparisonReliable: true, warmingUp: false, previousPeriodAvailable: true,
    lastSeenAt: '2026-07-22T10:42:00Z',
    changePercent: 18.4,
    hasComparison: true,
  },
  {
    id: 'q-a931b',
    queryId: '693019',
    serverId: 1,
    databaseId: 16384,
    fingerprint: 'a931bc20',
    title: 'Aktif ürün kataloğu araması',
    sqlPreview: "SELECT p.* FROM products p WHERE lower(p.name) LIKE '%' || $1 || '%'…",
    database: 'commerce',
    calls: 9204,
    avgDurationMs: 196,
    totalTimeMs: 1803984,
    dbLoadPercent: 5.7,
    sharedBlocksHit: 2_104_000,
    sharedBlocksRead: 320,
    tempBlocksWritten: 0,
    walBytes: 0,
    cpu: { capability: { available: true, version: '2.3.2', dataAvailable: true, source: 'PoWA pg_stat_kcache', coverage: 'EXECUTION_ONLY', reason: 'CPU ve filesystem sayaçları kullanılabilir.' }, userTimeMs: 1_020_000, systemTimeMs: 180_000, totalTimeMs: 1_200_000, percentOfExecTime: 66.5, filesystemReadsBytes: 9_000_000, filesystemWritesBytes: 0, scoreIncluded: false },
    waits: demoWaits,
    impactScore: 68,
    priority: 'HIGH',
    severity: 'warning',
    observedFrom: '2026-07-21T10:41:00Z', observedTo: '2026-07-22T10:41:00Z', coveragePercent: 100,
    resetDetected: false, comparisonReliable: true, warmingUp: false, previousPeriodAvailable: true,
    lastSeenAt: '2026-07-22T10:41:00Z',
    changePercent: -6.2,
    hasComparison: true,
  },
  {
    id: 'q-df208',
    queryId: '913928',
    serverId: 1,
    databaseId: 16385,
    fingerprint: 'df208e14',
    title: 'Bekleyen ödeme mutabakatı',
    sqlPreview: 'SELECT p.provider, COUNT(*), SUM(p.amount) FROM payments p…',
    database: 'billing',
    calls: 3120,
    avgDurationMs: 882,
    totalTimeMs: 2751840,
    dbLoadPercent: 8.7,
    sharedBlocksHit: 920_000,
    sharedBlocksRead: 12_480,
    tempBlocksWritten: 182,
    walBytes: 4_800_000,
    cpu: { capability: { available: true, version: '2.3.2', dataAvailable: true, source: 'PoWA pg_stat_kcache', coverage: 'EXECUTION_ONLY', reason: 'CPU ve filesystem sayaçları kullanılabilir.' }, userTimeMs: 820_000, systemTimeMs: 240_000, totalTimeMs: 1_060_000, percentOfExecTime: 38.5, filesystemReadsBytes: 102_000_000, filesystemWritesBytes: 18_000_000, scoreIncluded: false },
    waits: demoWaits,
    impactScore: 88,
    priority: 'CRITICAL',
    severity: 'critical',
    observedFrom: '2026-07-21T10:38:00Z', observedTo: '2026-07-22T10:38:00Z', coveragePercent: 100,
    resetDetected: false, comparisonReliable: true, warmingUp: false, previousPeriodAvailable: true,
    lastSeenAt: '2026-07-22T10:38:00Z',
    changePercent: 31.7,
    hasComparison: true,
  },
  {
    id: 'q-44ce0',
    queryId: '281824',
    serverId: 1,
    databaseId: 16386,
    fingerprint: '44ce0f9b',
    title: 'Günlük stok hareketleri',
    sqlPreview: 'SELECT warehouse_id, product_id, SUM(delta) FROM stock_movements…',
    database: 'inventory',
    calls: 1440,
    avgDurationMs: 122,
    totalTimeMs: 175680,
    dbLoadPercent: 0.6,
    sharedBlocksHit: 680_000,
    sharedBlocksRead: 42,
    tempBlocksWritten: 0,
    walBytes: 120_000,
    cpu: { capability: { available: true, version: '2.3.2', dataAvailable: true, source: 'PoWA pg_stat_kcache', coverage: 'EXECUTION_ONLY', reason: 'CPU ve filesystem sayaçları kullanılabilir.' }, userTimeMs: 98_000, systemTimeMs: 12_000, totalTimeMs: 110_000, percentOfExecTime: 62.6, filesystemReadsBytes: 1_500_000, filesystemWritesBytes: 100_000, scoreIncluded: false },
    waits: demoWaits,
    impactScore: 54,
    priority: 'MEDIUM',
    severity: 'warning',
    observedFrom: '2026-07-21T10:32:00Z', observedTo: '2026-07-22T10:32:00Z', coveragePercent: 100,
    resetDetected: false, comparisonReliable: true, warmingUp: false, previousPeriodAvailable: true,
    lastSeenAt: '2026-07-22T10:32:00Z',
    changePercent: -22.8,
    hasComparison: true,
  },
  {
    id: 'q-f90c4',
    queryId: '1018340',
    serverId: 1,
    databaseId: 16387,
    fingerprint: 'f90c421e',
    title: 'Kullanıcı oturum doğrulaması',
    sqlPreview: 'SELECT id, role, last_login_at FROM users WHERE id = $1 AND active…',
    database: 'identity',
    calls: 45280,
    avgDurationMs: 8.4,
    totalTimeMs: 380352,
    dbLoadPercent: 1.2,
    sharedBlocksHit: 1_840_000,
    sharedBlocksRead: 8,
    tempBlocksWritten: 0,
    walBytes: 0,
    cpu: { capability: { available: true, version: '2.3.2', dataAvailable: true, source: 'PoWA pg_stat_kcache', coverage: 'EXECUTION_ONLY', reason: 'CPU ve filesystem sayaçları kullanılabilir.' }, userTimeMs: 250_000, systemTimeMs: 36_000, totalTimeMs: 286_000, percentOfExecTime: 75.2, filesystemReadsBytes: 180_000, filesystemWritesBytes: 0, scoreIncluded: false },
    waits: demoWaits,
    impactScore: 8,
    priority: 'LOW',
    severity: 'healthy',
    observedFrom: '2026-07-22T10:35:00Z', observedTo: '2026-07-22T10:43:00Z', coveragePercent: 0.56,
    resetDetected: false, comparisonReliable: false, warmingUp: true, previousPeriodAvailable: false,
    lastSeenAt: '2026-07-22T10:43:00Z',
    changePercent: null,
    hasComparison: false,
  },
  {
    id: 'q-11b2f',
    queryId: '725807',
    serverId: 1,
    databaseId: 16384,
    fingerprint: '11b2f891',
    title: 'Kampanya hedef kitle seçimi',
    sqlPreview: 'WITH customer_totals AS (SELECT customer_id, SUM(total)…',
    database: 'commerce',
    calls: 288,
    avgDurationMs: 2480,
    totalTimeMs: 714240,
    dbLoadPercent: 2.3,
    sharedBlocksHit: 420_000,
    sharedBlocksRead: 18_400,
    tempBlocksWritten: 740,
    walBytes: 0,
    cpu: { capability: { available: true, version: '2.3.2', dataAvailable: true, source: 'PoWA pg_stat_kcache', coverage: 'EXECUTION_ONLY', reason: 'CPU ve filesystem sayaçları kullanılabilir.' }, userTimeMs: 310_000, systemTimeMs: 120_000, totalTimeMs: 430_000, percentOfExecTime: 60.2, filesystemReadsBytes: 150_000_000, filesystemWritesBytes: 45_000_000, scoreIncluded: false },
    waits: demoWaits,
    impactScore: 86,
    priority: 'CRITICAL',
    severity: 'critical',
    observedFrom: '2026-07-21T10:24:00Z', observedTo: '2026-07-22T10:24:00Z', coveragePercent: 100,
    resetDetected: false, comparisonReliable: true, warmingUp: false, previousPeriodAvailable: true,
    lastSeenAt: '2026-07-22T10:24:00Z',
    changePercent: 9.8,
    hasComparison: true,
  },
]

export const demoOverview: OverviewStats = {
  databaseName: 'commerce-prod',
  environment: 'Üretim',
  lastCollectedAt: '2026-07-22T10:43:00Z',
  queriesAnalyzed: 1276,
  criticalQueries: 17,
  regressions: 6,
  databaseTimeHours: 28.4,
  latencyTrend: [
    { label: 'Pzt', value: 238 }, { label: 'Sal', value: 228 }, { label: 'Çar', value: 242 },
    { label: 'Per', value: 211 }, { label: 'Cum', value: 205 }, { label: 'Cmt', value: 191 },
    { label: 'Paz', value: 184 },
  ],
  recentActivity: [
    { id: 'a1', title: 'Toplama tamamlandı', detail: '1.276 sorgu örneği işlendi', occurredAt: '2026-07-22T10:43:00Z', tone: 'healthy' },
    { id: 'a2', title: 'Yeni kritik bulgu', detail: 'Ödeme mutabakatında sıralı tarama', occurredAt: '2026-07-22T10:38:00Z', tone: 'critical' },
    { id: 'a3', title: 'İyileştirme doğrulandı', detail: 'Stok sorgusu gecikmesi %23 düştü', occurredAt: '2026-07-22T09:52:00Z', tone: 'healthy' },
  ],
  opportunities: [
    { queryId: 'q-df208', title: 'Bekleyen ödeme mutabakatı', averageMs: 882, loadPercent: 18.4 },
    { queryId: 'q-7f21a', title: 'Sipariş geçmişi ve müşteri özeti', averageMs: 428, loadPercent: 14.2 },
    { queryId: 'q-11b2f', title: 'Kampanya hedef kitle seçimi', averageMs: 2480, loadPercent: 9.8 },
  ],
  topQueries: demoQueries.filter((query) => query.serverId === 1 && query.databaseId === 16384).slice(0, 4),
}

export const demoQueryDetails: Record<string, QueryDetail> = Object.fromEntries(
  demoQueries.map((query, index) => [query.id, {
    ...query,
    fullSql: index === 0
      ? `SELECT o.id, o.created_at, c.name,\n       SUM(oi.quantity * oi.price) AS total\nFROM orders o\nJOIN customers c ON c.id = o.customer_id\nJOIN order_items oi ON oi.order_id = o.id\nWHERE o.created_at >= $1\n  AND c.tenant_id = $2\nGROUP BY o.id, o.created_at, c.name\nORDER BY o.created_at DESC\nLIMIT 100;`
      : `${query.sqlPreview.replace('…', '')}\nWHERE created_at >= $1\nORDER BY created_at DESC\nLIMIT $2;`,
    firstSeenAt: '2026-07-08T07:20:00Z',
    durationDistribution: { available: false, reason: 'PoWA tekil yürütme sürelerinin dağılımını saklamıyor.' },
    rowsPerCall: 74,
    sharedBlocksHit: 8192,
    sharedBlocksRead: 1840,
    trend: [
      { label: '16 Tem', durationMs: query.avgDurationMs * 1.26, impactScore: Math.max(0, query.impactScore - 9) },
      { label: '17 Tem', durationMs: query.avgDurationMs * 1.14, impactScore: Math.max(0, query.impactScore - 7) },
      { label: '18 Tem', durationMs: query.avgDurationMs * 1.21, impactScore: Math.max(0, query.impactScore - 5) },
      { label: '19 Tem', durationMs: query.avgDurationMs * .98, impactScore: Math.max(0, query.impactScore - 4) },
      { label: '20 Tem', durationMs: query.avgDurationMs * 1.08, impactScore: Math.max(0, query.impactScore - 2) },
      { label: '21 Tem', durationMs: query.avgDurationMs * 1.02, impactScore: Math.max(0, query.impactScore - 1) },
      { label: '22 Tem', durationMs: query.avgDurationMs, impactScore: query.impactScore },
    ],
    scoreBreakdown: [
      { key: 'latency', label: 'Toplam süre', contribution: Math.min(25, Math.round(query.impactScore * .3)), maxContribution: 25, hint: 'Toplam çalışma süresinin etkisi' },
      { key: 'io', label: 'Okunan shared blok', contribution: Math.min(25, Math.round(query.impactScore * .25)), maxContribution: 25, hint: 'Shared blok okuma yükü' },
      { key: 'regression', label: 'Yavaşlama', contribution: Math.min(25, Math.round(query.impactScore * .2)), maxContribution: 25, hint: 'Önceki döneme göre değişim' },
      { key: 'frequency', label: 'Çağrı sıklığı', contribution: Math.min(25, Math.round(query.impactScore * .25)), maxContribution: 25, hint: 'Çağrı sayısının toplam etkisi' },
    ],
    comparison: [
      { metric: 'Ort. gecikme', before: query.avgDurationMs, after: query.avgDurationMs * .36, unit: 'ms', improvementPercent: 64 },
      { metric: 'Okunan blok', before: 1840, after: 312, unit: 'blok', improvementPercent: 83 },
      { metric: 'Tahmini maliyet', before: 8420, after: 2710, unit: 'cost', improvementPercent: 68 },
    ],
    findings: [
      { id: 'f1', severity: 'critical', title: 'Yüksek shared blok okuması', description: 'Bu sorgu seçili dönemde belirgin bir okuma yükü oluşturuyor.', recommendation: 'Sorgu planını gerçek parametreler ve buffer ölçümleriyle doğrulayın.' },
      { id: 'f2', severity: 'warning', title: 'Yüksek toplam çalışma süresi', description: 'Çağrı sayısı ve ortalama süre birlikte toplam etkiyi yükseltiyor.', recommendation: 'En yoğun kullanım senaryosunu ölçüp sorgu planındaki pahalı adımları inceleyin.' },
    ],
    predicates: {
      capability: {
        available: true,
        version: '2.1.4',
        dataAvailable: true,
        coverage: 'WHERE_AND_JOIN_SNAPSHOT',
        joinsAvailable: true,
        ddlGenerated: index === 0,
        reason: 'WHERE kanıtı PoWA’dan, JOIN kanıtı düşük yetkili reset-boundary snapshotter’dan gelir.',
        observedFrom: '2026-07-22T09:43:00Z',
        observedTo: '2026-07-22T10:43:00Z',
      },
      items: [{
        qualId: `demo-${index + 1}`,
        relationId: 16400 + index,
        schemaName: 'public',
        tableName: index === 0 ? 'orders' : 'events',
        columns: [index === 0 ? 'created_at' : 'event_type'],
        operatorOids: [1324],
        evalType: 'FILTER',
        occurrences: 1842,
        rowsProcessed: 2_400_000,
        rowsFiltered: 2_040_000,
        filterRatio: .85,
        observedFrom: '2026-07-22T09:43:00Z',
        observedTo: '2026-07-22T10:43:00Z',
        sampleCount: 120,
        signal: 'INDEX_CANDIDATE',
        recommendation: 'Yüksek eleme oranlı WHERE filtresi; HypoPG ve EXPLAIN ile sanal index faydasını doğrulayın.',
      }],
      joinCapability: {
        available: true,
        dataAvailable: index === 0,
        status: 'HEALTHY',
        lastSnapshotAt: '2026-07-22T10:43:00Z',
        lagSeconds: 5,
        captureMode: 'QUALSTATS_RESET_BOUNDARY',
        reason: 'JOIN outbox aktarımı sağlıklı; kanıt inceleme puanına dahil değildir.',
      },
      joins: index === 0 ? [{
        qualId: '9001',
        qualNodeId: '9002',
        leftRelationId: 16400,
        leftSchemaName: 'public',
        leftTableName: 'orders',
        leftColumnName: 'customer_id',
        rightRelationId: 16390,
        rightSchemaName: 'public',
        rightTableName: 'customers',
        rightColumnName: 'id',
        operatorOid: 410,
        operatorName: '=',
        btreeStrategy: 3,
        occurrences: 1842,
        rowsProcessed: 2_400_000,
        sampleCount: 120,
        observedFrom: '2026-07-22T09:43:00Z',
        observedTo: '2026-07-22T10:43:00Z',
        signal: 'FREQUENT_JOIN',
        scoreIncluded: false,
      }] : [],
      candidates: index === 0 ? [{
        candidateId: '11111111-1111-4111-8111-111111111111',
        serverId: query.serverId,
        databaseId: query.databaseId,
        queryId: query.queryId,
        relationId: 16400,
        schemaName: 'public',
        tableName: 'orders',
        method: 'btree',
        columns: ['status', 'customer_id'],
        operatorOids: [98, 410],
        orderingRule: 'SELECTIVE_EQUALITY_FILTER_THEN_JOIN',
        joinOccurrences: 1842,
        filterOccurrences: 1842,
        rowsProcessed: 2_400_000,
        rowsFiltered: 2_040_000,
        filterRatio: .85,
        sampleCount: 120,
        observedFrom: '2026-07-22T09:43:00Z',
        observedTo: '2026-07-22T10:43:00Z',
        confidence: 'HIGH',
        createIndexSql: 'CREATE INDEX CONCURRENTLY "idx_advisor_orders_demo" ON "public"."orders" USING btree ("status", "customer_id");',
        existingIndexChecked: false,
        runtimeFixtureAvailable: false,
        scoreIncluded: false,
      }] : [],
    },
  }]),
) as Record<string, QueryDetail>

const history = (values: number[]) => values.map((value, index) => ({
  label: `${index * 4}:00`,
  value,
}))

export const demoHealth: SystemHealth = {
  collectedAt: '2026-07-22T10:43:00Z',
  postgresVersion: '18.4',
  overall: 'warning',
  metrics: [
    { key: 'connections', label: 'Bağlantı kullanımı', value: 64, unit: '%', target: '< %80', severity: 'healthy', description: '128 / 200 bağlantı aktif', history: history([46, 48, 52, 58, 61, 64]) },
    { key: 'cache', label: 'Cache hit oranı', value: 98.7, unit: '%', target: '> %99', severity: 'warning', description: 'Son 24 saat paylaşımlı buffer', history: history([99.1, 99, 98.9, 98.8, 98.7, 98.7]) },
    { key: 'cpu', label: 'CPU kullanımı', value: 42, unit: '%', target: '< %75', severity: 'healthy', description: '15 dakika hareketli ortalama', history: history([28, 32, 31, 39, 46, 42]) },
    { key: 'storage', label: 'Disk kullanımı', value: 71, unit: '%', target: '< %80', severity: 'warning', description: '412 GB / 580 GB', history: history([68, 68.4, 69, 69.8, 70.4, 71]) },
  ],
  databases: [
    { serverId: 1, databaseId: 16384, name: 'commerce', sizeGb: 284, tableCount: 42, sequentialScans: 842, indexScans: 12042, deadTuples: 18240, signals: 0, severity: 'healthy' },
    { serverId: 1, databaseId: 16385, name: 'billing', sizeGb: 96, tableCount: 18, sequentialScans: 1184, indexScans: 8420, deadTuples: 92400, signals: 2, severity: 'warning' },
    { serverId: 1, databaseId: 16386, name: 'inventory', sizeGb: 32, tableCount: 23, sequentialScans: 96, indexScans: 7280, deadTuples: 4280, signals: 0, severity: 'healthy' },
  ],
  capabilities: [
    { key: 'seqScan', label: 'Seq Scan', available: true, source: 'PoWA pg_stat_all_tables' },
    { key: 'deadTuple', label: 'Dead tuple', available: true, source: 'PoWA pg_stat_all_tables' },
    { key: 'autovacuum', label: 'Autovacuum', available: true, source: 'PoWA pg_stat_all_tables' },
  ],
}

const demoCapabilityItems: CapabilityMatrixData['items'][number]['capabilities'] = [
  ['historicalMetrics', 'Historical metrics'], ['cpuMetrics', 'CPU metrics'], ['waitSampling', 'Wait sampling'],
  ['predicateMetrics', 'Predicate metrics'], ['joinSnapshot', 'JOIN snapshot'], ['hypopg', 'HypoPG'],
  ['sourceExplain', 'Source EXPLAIN'], ['cloneValidation', 'Clone validation'],
].map(([key, label]) => ({ key: key as CapabilityMatrixData['items'][number]['capabilities'][number]['key'], label, status: 'AVAILABLE', configured: true, healthy: true, dataAvailable: true, available: true, reasonCode: 'AVAILABLE', reason: 'Kullanılabilir.' }))

export const demoCapabilities: CapabilityMatrixData = {
  window: '24h',
  items: [{ serverId: 1, serverAlias: 'demo-source', databaseId: 16384, databaseName: 'commerce', capabilities: demoCapabilityItems }],
}

export const demoDatabaseOptimize: DatabaseOptimizeData = {
  window: '24h',
  scope: { serverId: 1, databaseId: 16384 },
  summary: { candidateGroups: 1, affectedQueries: 1, affectedLoadMs: 7_883_760, validatedGroups: 0 },
  items: [{
    groupId: 'demo-orders-status-customer', serverId: 1, serverAlias: 'demo-source', databaseId: 16384, databaseName: 'commerce', relationId: 16400,
    schemaName: 'public', tableName: 'orders', method: 'btree', columns: ['status', 'customer_id'], confidence: 'HIGH',
    createIndexSql: 'CREATE INDEX CONCURRENTLY "idx_advisor_orders_demo" ON "public"."orders" USING btree ("status", "customer_id");',
    representative: { candidateId: '11111111-1111-4111-8111-111111111111', queryId: '520730' }, affectedQueryCount: 1, affectedQueryIds: ['520730'], affectedLoadMs: 7_883_760,
    evidence: { joinOccurrences: 1842, filterOccurrences: 1842, sampleCount: 120, observedFrom: '2026-07-22T09:43:00Z', observedTo: '2026-07-22T10:43:00Z' },
    existingIndex: { status: 'NOT_CHECKED', reason: 'Canlı katalog kontrolü bekleniyor.' }, hypopg: { status: 'NOT_EVALUATED', reason: 'Henüz doğrulanmadı.' },
    maintenanceCost: { writeRows: 9200, writesPerHour: 383, risk: 'MEDIUM', walBytesEstimate: null, reason: 'WAL tahmini mevcut değil.' },
  }],
  page: 1, pageSize: 50, total: 1,
}
